### PR TITLE
Avoid nesting if statements in src/st_src/ism330dhcx_reg.c. Change comments to doxygen style.

### PR DESCRIPTION
**Pull request by jimmyberg**
Note that src/st_src/ism330dhcx_reg.c had a lot of nested if statements. This has been changed.
It is recommended to use `git diff --ignore-space-change` when reviewing the code.

### CODE REVIEW

**Comment by PaulZC** [comment]
Hi Jimmy (@jimmyberg ),

Thank you for submitting these changes. Unfortunately they are so extensive, GitHub can't display them. We will need to merge this into a test branch and review the changes offline. That will take some time...

If there are any important / essential changes - other than nice-to-haves - could you please point them out? I'd be happy to merge 589a32e - if we can separate out the many whitespace changes.

Best wishes,
Paul

**Comment by jimmyberg** [comment]
Hello Pail, @PaulZC
The most I highlight is that I removed all compiler warnings but did not change the library interface. So no change of function arguments etc.
This allows users to catch warnings of their own code.

Also, I made src/st_src/ism330dhcx_reg.c more readable. The nesting was too much. Now with a simple
``` C++
if (ret != 0)
    return ret;
```
It is clear to the reader that it will simply break when an error occurs.

**Comment by jimmyberg** [comment]
Hello Paul, @PaulZC

I would recommend adding?w=1 to the end of the URL when comparing files.
so:
https://github.com/sparkfun/SparkFun_6DoF_ISM330DHCX_Arduino_Library/pull/9/files?w=1

Kind regards,
Jimmy van den Berg

**Comment by PaulZC** [comment]
Hi Jimmy,

Thank you for the new commits - and for the ?w=1 trick! The changes are large, but I can now see all of them on GitHub.

I will ask my colleagues to review the changes.

Best wishes,
Paul

**Comment by kirk-sfe** [comment]
Hi -

Thanks for the work on this. A

Our code style is outline here. https://github.com/sparkfun/.github/blob/main/SFECodeStyleGuide.md

If there are issues with formatting, we'll make sure our code is meeting the goals set by this guide and run our auto-formatter against it. 

We don't see any compiler warnings - what version of Arduino and boards are you suing?

Additionally, a portion of this code is supplied by ST, and we want to keep this as is. 

If there are issues with the library. , we're happy to apply these in a separate, issue focus  PR(s).

Thanks!
-Kirk

**Comment by jimmyberg** [comment]
In Arduino, you may set the compiler warnings to "all". Then you will find that there are compiler warnings.

Can you explain what are "issue focus PR(s)"

**Pull request closed without merging**
